language: node_js

node_js: 10

notifications:
  email: false

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn --frozen-lockfile

script:
  - yarn test --maxWorkers=10

before_deploy:
  - git config --global user.name "seek-oss-ci";
  - git config --global user.email "opensource@seek.com.au";
  - git remote set-url origin "https://${GH_TOKEN}@github.com/seek-oss/treat.git"
  - git checkout master
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
  - yarn build-docs

deploy:
  - provider: script
    script: yarn release --yes
    skip_cleanup: true
    on:
      branch: master
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    keep_history: true
    local_dir: ./site/dist
    on:
      branch: master
